# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# setup_travis
default_platform(:ios)


platform :ios do

  desc 'Runs analysis on the code using swiftlint'
  lane :analysis do
    swiftlint(
      mode: :lint,
      executable: 'Pods/SwiftLint/swiftlint',
      config_file: '.swiftlint.yml'
    )
  end

  desc 'Runs unit tests'
  lane :test do
    scan(
      scheme: 'TreeTrackerTests',
      devices: ["iPhone 6s"]
    )
  end

  desc 'Builds the project'
  lane :build do
    gym(
      scheme: "TreeTracker",
      skip_codesigning: true
    )
  end
end
